### ISSUE TITLE
Can we have a language option in this extension?

### ISSUE THREAD

**Issue by crossnova** [joe-damore/close-other-tabs-item#11]
I'm running in Traditional Chinese environment and I don't want to see Simplified Chinese button in my menu.
(for now it seems forcibly showing SC UI name and I can't change it. this could be an issue around my place too)
Can we have an option to turn it back to English rather than automatically decided by windows language or else reason? 
Thanks.

**Comment by crossnova** [comment]
In case it helps,

{
  "extensionName": {
    "message": "關閉其他分頁",
    "description": "Extension name"
  },
  "extensionDescription": {
    "message": "新增「關閉其他分頁」到分頁右鍵選單",
    "description": "Extension description"
  },
  "menuItemTitle": {
    "message": "關閉其他分頁",
    "description": "Context menu item title"
  }
}

above is the Traditional Chinese version translation.
also Jap ver.
"他のタブをすべて閉じる"
”「他のタブをすべて閉じる」をタブの右クリックメニューに追加”
”他のタブをすべて閉じる”

**Comment by joe-damore** [comment]
Hi @crossnova, thanks for opening this issue and sharing those translations for Traditional Chinese and Japanese!

I'll add these and try to have a release submitted to Mozilla for review this weekend.

Is there any chance you'd be willing to post similar translations for my [Close Tabs to the Right](https://github.com/joe-damore/close-tabs-to-the-right-item) and [Close Tabs to the Left](https://github.com/joe-damore/close-tabs-to-the-left-item) extensions? I'd love to keep parity between the three extensions, but have been hesitant to rely on tools like Google Translate out of fear I might add a poor translation.

**Comment by crossnova** [comment]
I added 2 pull request under each extension, since it's my first time adding these things so if there's any mistake plz correct them for me.

Thanks for replying.

**Comment by joe-damore** [comment]
@crossnova Just submitted version 1.0.4 of this extension to Mozilla, which includes your Traditional Chinese and Japanese translations -- it may take Mozilla a few days to review the extension, but I'll update here once that's complete.

Thanks again for contributing these translations, and for the PRs on the other two extensions! I will submit similar updates for them soon :)

Take care!

**Edit:** Just got notification that [these changes are now available](https://addons.mozilla.org/en-US/firefox/addon/close-other-tabs-item/)!
